font_size 10
disable_ligatures never
font_family FiraCode Nerd Font
cursor_shape beam
cursor_blink_interval -1 cubic-bezier(0.25, 0.1, 0.25, 1)
cursor_trail 1
cursor_trail_decay 0.1 0.4
# Tab bar
tab_bar_edge bottom
tab_bar_style separator
tab_separator "  │  "
tab_bar_background #111122
active_tab_background #111122
active_tab_foreground #ffffff
active_tab_font_style bold
inactive_tab_background #111122
inactive_tab_foreground #cccccc
inactive_tab_font_style normal
tab_title_template " {index}: {title} "
tab_bar_min_tabs 1

# Tab keybindings
map ctrl+shift+t launch --type=tab --cwd=current
map ctrl+shift+w close_window
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab
map ctrl+alt+1 goto_tab 1
map ctrl+alt+2 goto_tab 2
map ctrl+alt+3 goto_tab 3
map ctrl+alt+4 goto_tab 4
map ctrl+alt+5 goto_tab 5
map ctrl+alt+6 goto_tab 6
map ctrl+alt+7 goto_tab 7
map ctrl+alt+8 goto_tab 8
map ctrl+alt+9 goto_tab 9
